sudo: required
services:
- docker
language: python
python:
- '3.6'
cache: pip
install:
- pip install pipenv
- pipenv install --ignore-pipfile --dev
script:
- pipenv run make tests
- pipenv run make html
deploy:
  provider: pypi
  skip_existing: true
  user: tillahoffmann
  password:
    secure: yO2h21yzPnHFyLETmvlLuBrRWPmR0HWAPZ6gJyOkf72Q6G2/ZKDd2GaF28kCE8I8hg64o4w96WcNgdbdaleUJkAT2aIRiNG3hepJ/oE8rQe7D8XK99OdOcE3PdaOZFQh0KenjjylJw6/ITXufZ6xofjLKPmVx0mvb/QUeqO6hBWUtCo826xVqAE0ls/fhT8VPq+tRKuk4DsPuINJhTrvz582+AdjZW5OJg3Bh+MkfwVdAQpzy9QM9sX9txyV4sWGy64TUvPyOcKQGtQC2MxIj8MsbYDY484sThgIvd3nMRyluspcIN8vimwUT0IDFaMEn8b/yRoTdc43nIFjP0gDbwpctwETL5E6TIvLE2gkVNLibXZBqZrXN3m1oV+sg9YZScSQJoj1esh74l4BAv+1r6Pf82iiX0F8vYAk1Jfs0uCI3Y4fng0D9iJtciYIuNzOZ+MmMoQ8sy5swN9BVvzYY+YsjwE2mx/vpoNTF0G99NcJYXLnIdnRTWHkiYjJPaUzG5Rh/oVl3ySskl9EJAVnEY05i/lemk7uEW9wkeCvES2dEiiNwqNn+6pW2hK0/6lPFHIW7Ji8bL58i+YK6S5yUPU1OVSFuAAtX4QPo6U5GyZN746UdUfcPRtN15RYWaKF/YRVz/93/X1KkVNLigUCJPCBvsvC03HMfZxEOmtt99Q=
